DELETE FROM products;

INSERT INTO products (
    product_id,
    name,
    category,
    price,
    stock_status,
    stock_quantity,
    brand,
    rating,
    image_url,
    description,
    sort_order
) VALUES
(
    'PRD-SNK-001',
    'Daily Runner Sneakers',
    'shoes',
    89000,
    'IN_STOCK',
    36,
    'Northline',
    4.7,
    '/assets/products/daily-runner-sneakers.svg',
    'Lightweight sneakers for daily commuting and weekend walks.',
    10
),
(
    'PRD-BAG-014',
    'City Commuter Backpack',
    'bags',
    129000,
    'LOW_STOCK',
    4,
    'UrbanTrail',
    4.5,
    '/assets/products/city-commuter-backpack.svg',
    'Compact backpack with laptop storage and travel-ready pockets.',
    20
),
(
    'PRD-ELC-042',
    'Noise Canceling Earbuds',
    'electronics',
    159000,
    'SOLD_OUT',
    0,
    'SoundPeak',
    4.8,
    '/assets/products/noise-canceling-earbuds.svg',
    'Wireless earbuds tuned for focus, calls, and transit noise.',
    30
),
(
    'PRD-WTC-018',
    'Focus Timer Watch',
    'electronics',
    119000,
    'IN_STOCK',
    18,
    'MonoClock',
    4.4,
    '/assets/products/focus-timer-watch.svg',
    'Minimal smart timer watch for work blocks and light activity.',
    40
),
(
    'PRD-OUT-027',
    'Packable Rain Jacket',
    'outerwear',
    98000,
    'IN_STOCK',
    27,
    'CloudShell',
    4.6,
    '/assets/products/packable-rain-jacket.svg',
    'Water-resistant jacket that folds into a compact travel pouch.',
    50
),
(
    'PRD-HOM-033',
    'Desk Mood Lamp',
    'home',
    69000,
    'LOW_STOCK',
    3,
    'WarmDesk',
    4.3,
    '/assets/products/desk-mood-lamp.svg',
    'Soft desk lamp with warm light modes for evening work.',
    60
),
(
    'PRD-SHO-002',
    'Trail Grip Hiking Shoes',
    'shoes',
    142000,
    'IN_STOCK',
    24,
    'RidgeWay',
    4.6,
    '/assets/products/placeholder.svg',
    'Durable hiking shoes with grippy outsoles for wet and rocky trails.',
    70
),
(
    'PRD-SHO-003',
    'Canvas Low-Top Sneakers',
    'shoes',
    59000,
    'IN_STOCK',
    48,
    'StreetForm',
    4.2,
    '/assets/products/placeholder.svg',
    'Clean canvas sneakers with cushioned insoles for everyday outfits.',
    80
),
(
    'PRD-SHO-004',
    'Leather Penny Loafers',
    'shoes',
    178000,
    'LOW_STOCK',
    2,
    'Atelier Row',
    4.5,
    '/assets/products/placeholder.svg',
    'Polished leather loafers designed for office wear and dinners out.',
    90
),
(
    'PRD-SHO-005',
    'Recovery Slide Sandals',
    'shoes',
    45000,
    'IN_STOCK',
    67,
    'FlexBay',
    4.1,
    '/assets/products/placeholder.svg',
    'Soft recovery slides with arch support for post-workout comfort.',
    100
),
(
    'PRD-SHO-006',
    'Waterproof Chelsea Boots',
    'shoes',
    189000,
    'SOLD_OUT',
    0,
    'HarborMade',
    4.7,
    '/assets/products/placeholder.svg',
    'Weather-ready Chelsea boots with sealed seams and pull tabs.',
    110
),
(
    'PRD-SHO-007',
    'Knit Training Sneakers',
    'shoes',
    99000,
    'LOW_STOCK',
    5,
    'MoveLab',
    4.4,
    '/assets/products/placeholder.svg',
    'Breathable knit sneakers built for gym sessions and quick errands.',
    120
),
(
    'PRD-SHO-008',
    'Classic Court Shoes',
    'shoes',
    76000,
    'IN_STOCK',
    31,
    'Baseline',
    4.3,
    '/assets/products/placeholder.svg',
    'Retro court-inspired shoes with a padded collar and rubber cupsole.',
    130
),
(
    'PRD-SHO-009',
    'Suede Desert Boots',
    'shoes',
    132000,
    'IN_STOCK',
    16,
    'SableWorks',
    4.5,
    '/assets/products/placeholder.svg',
    'Soft suede desert boots with lightweight crepe-style soles.',
    140
),
(
    'PRD-SHO-010',
    'Mesh Walking Shoes',
    'shoes',
    83000,
    'LOW_STOCK',
    1,
    'StepKind',
    4.2,
    '/assets/products/placeholder.svg',
    'Light mesh walking shoes with a stable heel and flexible forefoot.',
    150
),
(
    'PRD-SHO-011',
    'Premium Running Spikes',
    'shoes',
    214000,
    'SOLD_OUT',
    0,
    'TrackNorth',
    4.8,
    '/assets/products/placeholder.svg',
    'Race-day running spikes tuned for speed workouts and track events.',
    160
),
(
    'PRD-BAG-015',
    'Weekend Duffel Bag',
    'bags',
    118000,
    'IN_STOCK',
    22,
    'CarryField',
    4.6,
    '/assets/products/placeholder.svg',
    'Roomy duffel bag with shoe storage and a padded shoulder strap.',
    170
),
(
    'PRD-BAG-016',
    'Minimal Crossbody Pouch',
    'bags',
    54000,
    'IN_STOCK',
    39,
    'PocketLane',
    4.3,
    '/assets/products/placeholder.svg',
    'Compact crossbody pouch for phone, keys, wallet, and transit cards.',
    180
),
(
    'PRD-BAG-017',
    'Structured Tote Bag',
    'bags',
    146000,
    'LOW_STOCK',
    3,
    'Maison Grid',
    4.5,
    '/assets/products/placeholder.svg',
    'Structured tote with a laptop sleeve and polished hardware details.',
    190
),
(
    'PRD-BAG-018',
    'Roll-Top Bike Backpack',
    'bags',
    154000,
    'IN_STOCK',
    17,
    'VeloPack',
    4.7,
    '/assets/products/placeholder.svg',
    'Water-resistant roll-top backpack with reflective commuter panels.',
    200
),
(
    'PRD-BAG-019',
    'Travel Organizer Set',
    'bags',
    39000,
    'IN_STOCK',
    72,
    'PackWell',
    4.2,
    '/assets/products/placeholder.svg',
    'Three-piece organizer set for cables, toiletries, and small gear.',
    210
),
(
    'PRD-BAG-020',
    'Leather Card Wallet',
    'bags',
    68000,
    'SOLD_OUT',
    0,
    'NobleFold',
    4.4,
    '/assets/products/placeholder.svg',
    'Slim leather card wallet with a quick-access front pocket.',
    220
),
(
    'PRD-BAG-021',
    'Camera Sling Bag',
    'bags',
    167000,
    'LOW_STOCK',
    4,
    'FrameCarry',
    4.8,
    '/assets/products/placeholder.svg',
    'Protective camera sling with adjustable dividers and side access.',
    230
),
(
    'PRD-BAG-022',
    'Gym Drawstring Pack',
    'bags',
    32000,
    'IN_STOCK',
    58,
    'ActiveLoop',
    4.0,
    '/assets/products/placeholder.svg',
    'Light drawstring pack with a ventilated pocket for training gear.',
    240
),
(
    'PRD-BAG-023',
    'Carry-On Spinner Case',
    'bags',
    238000,
    'IN_STOCK',
    12,
    'AeroLuggage',
    4.6,
    '/assets/products/placeholder.svg',
    'Hard-shell carry-on with quiet spinner wheels and interior dividers.',
    250
),
(
    'PRD-BAG-024',
    'Quilted Mini Shoulder Bag',
    'bags',
    97000,
    'LOW_STOCK',
    2,
    'LunaVine',
    4.3,
    '/assets/products/placeholder.svg',
    'Compact quilted shoulder bag with a chain strap and magnetic flap.',
    260
),
(
    'PRD-ELC-043',
    'Portable Bluetooth Speaker',
    'electronics',
    88000,
    'IN_STOCK',
    34,
    'SoundPeak',
    4.5,
    '/assets/products/placeholder.svg',
    'Portable speaker with deep bass, water resistance, and all-day battery.',
    270
),
(
    'PRD-ELC-044',
    'USB-C GaN Charger 65W',
    'electronics',
    49000,
    'IN_STOCK',
    81,
    'VoltNest',
    4.6,
    '/assets/products/placeholder.svg',
    'Compact GaN charger with dual USB-C ports for laptops and phones.',
    280
),
(
    'PRD-ELC-045',
    'Mechanical Wireless Keyboard',
    'electronics',
    139000,
    'LOW_STOCK',
    5,
    'KeyForge',
    4.7,
    '/assets/products/placeholder.svg',
    'Low-latency wireless keyboard with hot-swap switches and quiet foam.',
    290
),
(
    'PRD-ELC-046',
    'Ergonomic Vertical Mouse',
    'electronics',
    62000,
    'IN_STOCK',
    46,
    'CursorLab',
    4.2,
    '/assets/products/placeholder.svg',
    'Vertical mouse shaped to reduce wrist strain during long workdays.',
    300
),
(
    'PRD-ELC-047',
    'Smart Home Hub Mini',
    'electronics',
    79000,
    'SOLD_OUT',
    0,
    'Nestory',
    4.1,
    '/assets/products/placeholder.svg',
    'Compact home hub for lights, sensors, scenes, and voice routines.',
    310
),
(
    'PRD-ELC-048',
    '4K Action Camera',
    'electronics',
    279000,
    'LOW_STOCK',
    2,
    'PeakFrame',
    4.5,
    '/assets/products/placeholder.svg',
    'Rugged 4K action camera with stabilization and waterproof housing.',
    320
),
(
    'PRD-ELC-049',
    'Fitness Band Pro',
    'electronics',
    99000,
    'IN_STOCK',
    28,
    'PulseArc',
    4.4,
    '/assets/products/placeholder.svg',
    'Slim fitness band with health tracking, sleep insights, and GPS sync.',
    330
),
(
    'PRD-ELC-050',
    'Compact Photo Printer',
    'electronics',
    128000,
    'IN_STOCK',
    15,
    'PrintNest',
    4.3,
    '/assets/products/placeholder.svg',
    'Small wireless printer for instant phone photos and travel journals.',
    340
),
(
    'PRD-ELC-051',
    'Dual Monitor Dock',
    'electronics',
    219000,
    'LOW_STOCK',
    4,
    'DeskPort',
    4.6,
    '/assets/products/placeholder.svg',
    'USB-C dock with dual display output, Ethernet, and fast charging.',
    350
),
(
    'PRD-ELC-052',
    'E-Reader Glow 7',
    'electronics',
    189000,
    'SOLD_OUT',
    0,
    'Readly',
    4.7,
    '/assets/products/placeholder.svg',
    'Seven-inch e-reader with warm front light and weeks of battery life.',
    360
),
(
    'PRD-OUT-028',
    'Wool Blend Overcoat',
    'outerwear',
    268000,
    'IN_STOCK',
    14,
    'Northline',
    4.7,
    '/assets/products/placeholder.svg',
    'Tailored wool blend overcoat with a clean silhouette for cold days.',
    370
),
(
    'PRD-OUT-029',
    'Lightweight Puffer Vest',
    'outerwear',
    112000,
    'IN_STOCK',
    26,
    'CloudShell',
    4.4,
    '/assets/products/placeholder.svg',
    'Layer-friendly puffer vest with recycled fill and secure pockets.',
    380
),
(
    'PRD-OUT-030',
    'Fleece Zip Jacket',
    'outerwear',
    87000,
    'LOW_STOCK',
    5,
    'SummitLoop',
    4.3,
    '/assets/products/placeholder.svg',
    'Soft fleece jacket for morning walks, cabins, and casual layering.',
    390
),
(
    'PRD-OUT-031',
    'Denim Trucker Jacket',
    'outerwear',
    126000,
    'IN_STOCK',
    21,
    'BlueAnchor',
    4.2,
    '/assets/products/placeholder.svg',
    'Classic denim trucker jacket with sturdy buttons and chest pockets.',
    400
),
(
    'PRD-OUT-032',
    'Reversible Bomber Jacket',
    'outerwear',
    174000,
    'SOLD_OUT',
    0,
    'MetroLayer',
    4.5,
    '/assets/products/placeholder.svg',
    'Reversible bomber jacket with smooth nylon on one side and quilted lining.',
    410
),
(
    'PRD-OUT-033',
    'Longline Down Parka',
    'outerwear',
    329000,
    'LOW_STOCK',
    2,
    'PolarField',
    4.8,
    '/assets/products/placeholder.svg',
    'Warm longline parka with down insulation and an adjustable storm hood.',
    420
),
(
    'PRD-OUT-034',
    'Softshell Utility Jacket',
    'outerwear',
    149000,
    'IN_STOCK',
    19,
    'TrailAxis',
    4.4,
    '/assets/products/placeholder.svg',
    'Stretch softshell jacket with utility pockets and wind resistance.',
    430
),
(
    'PRD-OUT-035',
    'Cropped Harrington Jacket',
    'outerwear',
    138000,
    'IN_STOCK',
    23,
    'OldMarket',
    4.1,
    '/assets/products/placeholder.svg',
    'Cropped Harrington jacket with a plaid lining and neat collar.',
    440
),
(
    'PRD-OUT-036',
    'Technical Shell Anorak',
    'outerwear',
    196000,
    'LOW_STOCK',
    3,
    'CloudShell',
    4.6,
    '/assets/products/placeholder.svg',
    'Half-zip shell anorak with taped zippers and adjustable cuffs.',
    450
),
(
    'PRD-OUT-037',
    'Linen Blend Chore Coat',
    'outerwear',
    109000,
    'IN_STOCK',
    32,
    'PlainWorks',
    4.2,
    '/assets/products/placeholder.svg',
    'Breathable chore coat with roomy patch pockets for transitional weather.',
    460
),
(
    'PRD-HOM-034',
    'Ceramic Aroma Diffuser',
    'home',
    58000,
    'IN_STOCK',
    44,
    'WarmDesk',
    4.4,
    '/assets/products/placeholder.svg',
    'Quiet ceramic diffuser with mist control and a soft night light.',
    470
),
(
    'PRD-HOM-035',
    'Cotton Percale Sheet Set',
    'home',
    92000,
    'LOW_STOCK',
    4,
    'RestHouse',
    4.6,
    '/assets/products/placeholder.svg',
    'Crisp cotton percale sheet set with breathable everyday comfort.',
    480
),
(
    'PRD-HOM-036',
    'Stackable Storage Bins',
    'home',
    36000,
    'IN_STOCK',
    63,
    'TidyNorth',
    4.1,
    '/assets/products/placeholder.svg',
    'Stackable storage bins for pantry shelves, closets, and utility rooms.',
    490
),
(
    'PRD-HOM-037',
    'Acacia Serving Board',
    'home',
    42000,
    'IN_STOCK',
    37,
    'TableGrove',
    4.5,
    '/assets/products/placeholder.svg',
    'Acacia wood serving board sized for cheese, bread, and appetizers.',
    500
),
(
    'PRD-HOM-038',
    'Cordless Hand Vacuum',
    'home',
    119000,
    'SOLD_OUT',
    0,
    'CleanPulse',
    4.3,
    '/assets/products/placeholder.svg',
    'Cordless hand vacuum for crumbs, car seats, and tight corners.',
    510
),
(
    'PRD-HOM-039',
    'Matte Dinnerware Set',
    'home',
    134000,
    'IN_STOCK',
    18,
    'TableGrove',
    4.6,
    '/assets/products/placeholder.svg',
    'Sixteen-piece matte dinnerware set with dinner plates, bowls, and mugs.',
    520
),
(
    'PRD-HOM-040',
    'Adjustable Laptop Stand',
    'home',
    64000,
    'LOW_STOCK',
    5,
    'DeskPort',
    4.4,
    '/assets/products/placeholder.svg',
    'Foldable aluminum laptop stand with adjustable height and angle.',
    530
),
(
    'PRD-HOM-041',
    'Memory Foam Pillow',
    'home',
    73000,
    'IN_STOCK',
    29,
    'RestHouse',
    4.5,
    '/assets/products/placeholder.svg',
    'Contoured memory foam pillow with a washable cooling cover.',
    540
),
(
    'PRD-HOM-042',
    'Minimal Wall Clock',
    'home',
    47000,
    'IN_STOCK',
    42,
    'MonoClock',
    4.0,
    '/assets/products/placeholder.svg',
    'Quiet wall clock with slim markers and a clean matte frame.',
    550
),
(
    'PRD-HOM-043',
    'Modular Bookshelf Unit',
    'home',
    186000,
    'LOW_STOCK',
    2,
    'RoomGrid',
    4.7,
    '/assets/products/placeholder.svg',
    'Modular bookshelf unit that expands horizontally for living rooms or studies.',
    560
),
(
    'PRD-SHO-012',
    'All-Weather Trek Sandals',
    'shoes',
    71000,
    'IN_STOCK',
    33,
    'RidgeWay',
    4.1,
    '/assets/products/placeholder.svg',
    'Adjustable trek sandals with quick-dry straps and cushioned footbeds.',
    570
),
(
    'PRD-BAG-025',
    'Expandable Laptop Briefcase',
    'bags',
    132000,
    'IN_STOCK',
    20,
    'UrbanTrail',
    4.4,
    '/assets/products/placeholder.svg',
    'Expandable briefcase with a padded laptop bay and luggage pass-through.',
    580
),
(
    'PRD-ELC-053',
    'Wireless Charging Pad Trio',
    'electronics',
    74000,
    'LOW_STOCK',
    3,
    'VoltNest',
    4.2,
    '/assets/products/placeholder.svg',
    'Three-device wireless charging pad for phone, earbuds, and watch.',
    590
),
(
    'PRD-OUT-038',
    'Waterproof Field Coat',
    'outerwear',
    221000,
    'IN_STOCK',
    11,
    'HarborMade',
    4.6,
    '/assets/products/placeholder.svg',
    'Waterproof field coat with a corduroy collar and oversized cargo pockets.',
    600
);
