CREATE TABLE IF NOT EXISTS order_audit (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   VARCHAR(80)  NOT NULL,
    product_id VARCHAR(80)  NOT NULL,
    quantity   INTEGER      NOT NULL,
    user_id    VARCHAR(120) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS products;

CREATE TABLE IF NOT EXISTS products (
    product_id   VARCHAR(80) PRIMARY KEY,
    name         VARCHAR(160) NOT NULL,
    category     VARCHAR(80)  NOT NULL,
    price        INTEGER      NOT NULL,
    stock_status VARCHAR(40)  NOT NULL,
    stock_quantity INTEGER    NOT NULL DEFAULT 0,
    brand        VARCHAR(120) NOT NULL,
    rating       DOUBLE PRECISION NOT NULL,
    image_url    VARCHAR(255),
    description  VARCHAR(500),
    sort_order   INTEGER      NOT NULL DEFAULT 100,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
